### ISSUE TITLE
Usernames should not be case sensitive on login

### ISSUE THREAD

**Issue by allinfinite** [villagescc/villagescc2.0#44]

**Comment by fpSpindola** [comment]
Done

**Comment by allinfinite** [comment]
This still doesn't work.. Users should be able to login with email addresses, too..
