### ISSUE TITLE
item search should include tags enhancement

### ISSUE THREAD

**Issue by allinfinite** [villagescc/villagescc2.0#6]

**Comment by fpSpindola** [comment]
Done

**Comment by allinfinite** [comment]
It looks like searching by tags still isn't working and displaying multiples..
![screen shot 2017-11-24 at 8 19 20 am](https://user-images.githubusercontent.com/2475429/33220929-3408b518-d0f0-11e7-80e3-7de3a3d51a83.png)
![screen shot 2017-11-24 at 8 18 51 am](https://user-images.githubusercontent.com/2475429/33220935-3843336a-d0f0-11e7-89be-f064eee352d6.png)
